import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
import * as model from '../public/assets/model.js';import * as charts from '../public/assets/charts.js';import * as exports from '../public/assets/export.js';
function screen(role){
 const app={innerHTML:'',addEventListener(){}},modal={innerHTML:'',addEventListener(){},showModal(){},close(){}},toast={};
 const context=vm.createContext({...model,...charts,...exports,console,URLSearchParams,setTimeout,clearTimeout,document:{querySelector:s=>({'#app':app,'#modal':modal,'#toast':toast}[s]),addEventListener(){}}});
 let script=readFileSync('public/assets/app.js','utf8').replace(/^import .*;\n/gm,'');script=script.replace(/start\(\);\s*$/,'globalThis.screenTest={state,render,load,fundingDialog,pageCsvRows};');vm.runInContext(script,context);
 const api=context.screenTest;api.state.user={role,display_name:role};api.state.data={...JSON.parse(readFileSync('public/assets/demo-data.json')),settings:[],criteria:[],synced_at:new Date().toISOString()};api.state.year='2568';api.state.compareA='2567';api.state.compareB='2568';api.state.admin={users:[],audit:[],deleted:[]};return {...api,app,context};
}
test('Teacher funding screen offers add and edit, omits delete and admin menus',()=>{const s=screen('TEACHER');s.state.page='funding';s.render();assert.ok(s.app.innerHTML.includes('data-action="add-funding"'));assert.ok(s.app.innerHTML.includes('data-action="edit-funding"'));assert.ok(!s.app.innerHTML.includes('data-action="delete-funding"'));assert.ok(!s.app.innerHTML.includes('data-page="users"'));});
test('Owner read only, admin includes delete and system pages',()=>{const owner=screen('OWNER');owner.state.page='funding';owner.render();assert.ok(!owner.app.innerHTML.includes('data-action="add-funding"'));assert.ok(!owner.app.innerHTML.includes('data-action="edit-funding"'));const admin=screen('ADMIN');admin.state.page='funding';admin.render();assert.ok(admin.app.innerHTML.includes('data-action="delete-funding"'));assert.ok(admin.app.innerHTML.includes('data-page="users"'));});
test('every page renders against real seed; inaccessible page redirects to overview',()=>{const s=screen('ADMIN');for(const page of ['dashboard','funding','compare','faculty','reports','faculties','users','settings','audit']){s.state.page=page;s.render();assert.ok(s.app.innerHTML.includes('R-FUND'));assert.ok(!s.app.innerHTML.includes('undefined'));assert.ok(!s.app.innerHTML.includes('NaN'));}const teacher=screen('TEACHER');teacher.state.page='users';teacher.render();assert.equal(teacher.state.page,'dashboard');});
test('all-years filter survives reload instead of silently reverting to latest',async()=>{const s=screen('TEACHER');s.state.year='';s.context.fetch=async()=>({json:async()=>({ok:true,data:s.state.data})});await s.load();assert.equal(s.state.year,'');});

test('every data page offers page-specific CSV and print/PDF controls',()=>{const s=screen('ADMIN');for(const page of ['dashboard','funding','compare','faculty','reports','faculties','users','settings','audit']){s.state.page=page;s.render();assert.ok(s.app.innerHTML.includes('data-action="page-csv"'));assert.ok(s.app.innerHTML.includes('data-action="print"'));assert.ok(s.app.innerHTML.includes('class="print-context"'));assert.ok(Array.isArray(s.pageCsvRows()));}});
test('CSV respects faculty/year scope and exports only safe user fields',()=>{const s=screen('ADMIN');s.state.page='dashboard';assert.equal(s.pageCsvRows().length,15);s.state.faculty='FAC001';assert.equal(s.pageCsvRows().length,2);s.state.page='faculty';assert.equal(s.pageCsvRows().length,3);s.state.page='compare';assert.equal(s.pageCsvRows().length,2);s.state.page='users';s.state.admin.users=[{username:'admin',display_name:'Admin',role:'ADMIN',active:true,password_hash:'secret',password_salt:'private'}];assert.equal(s.pageCsvRows().length,2);assert.ok(!JSON.stringify(s.pageCsvRows()).includes('secret'));assert.ok(!JSON.stringify(s.pageCsvRows()).includes('private'));});
